language: java
jdk:
  - openjdk11
services:
  - docker
  - postgresql

before_install:
#   create user myuser with encrypted password 'mypass';
#  - grant all privileges on database mydb to myuser
#  - psql -c 'create user ds_suite with encrypted password \'ds_suite\'';
  - psql -c "create user ds_suite_admin with encrypted password 'ds_suite_123';"
  - psql -c 'create database ds_suite;'
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull openjdk:11-jre-slim-sid
script:
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install
  - ./mvnw heroku:deploy jib:build -P deploy-heroku,deploy-docker

after_success:
  - bash <(curl -s https://codecov.io/bash)