language: java
jdk:
  - openjdk11
services:
  - docker
  - postgresql

before_install:
  - psql -c "create user ds_suite with encrypted password 'ds_suite_123';"
  - psql -c "create user ds_suite_test with encrypted password 'ds_suite_test_123';"
  - psql -c 'create database ds_suite_test_db;'
  - psql -c 'create database ds_suite;'
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE "ds_suite_test_db" to ds_suite_test;"
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE "ds_suite" to ds_suite;"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull openjdk:11-jre-slim-sid
script:
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install
  - ./mvnw heroku:deploy jib:build -P deploy-heroku,deploy-docker

after_success:
  - bash <(curl -s https://codecov.io/bash)
