node{
    stage('Git CheckOut'){
        echo 'cloning the repo'
        git '{github_url}'

    }
    stage("Build Artifact"){
        echo 'Building the application'
        sh 'npm install'

    }
    stage('Test'){
        sh 'npm test'
    }
    stage("Build Docker"){
        echo 'building image for heroku registry'
        sh "docker build -t {app_name} ."
    }
    stage("Deploy Heroku"){
        echo 'Deploying image to heroku'

        withVault(configuration: [timeout: 60, vaultCredentialId: 'vault-token', vaultUrl: '{vault_url}'], vaultSecrets: [[path: 'heroku/herokulogin', secretValues: [[vaultKey: 'HEROKU_USERNAME'], [vaultKey: 'HEROKU_TOKEN']]]]) {
            sh "docker login --username $HEROKU_USERNAME --password $HEROKU_TOKEN registry.heroku.com"
    }
     sh "docker ps"
     sh "docker container ls"
     sh "docker tag pivotaldevops:latest registry.heroku.com/{app_name}/web"
     sh "docker push registry.heroku.com/{app_name}/web"
     sh '''
        imageId=$(docker inspect registry.heroku.com/{app_name}/web --format={{.Id}})
        payload='{"updates":[{"type":"web","docker_image":"'"$imageId"'"}]}'
        curl -n -X PATCH https://api.heroku.com/apps/{app_name}/formation \
        -d "$payload" \
        -H "Content-Type: application/json" \
        -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
        -H "Authorization: Bearer $GIT_USERNAME"
        '''


    }

      post {
        // Always runs. And it runs before any of the other post conditions.
        always {
          // Let's wipe out the workspace before we finish!
          deleteDir()
        }

        success{
            mail bcc: 'devopsteam@gmail.com', body: 'the build was a sucessfull one', cc: 'teamlead@mail.com', from: '', replyTo: '', subject: 'success', to: 'culprit@mail.com'

        }
        failure{
            mail bcc: 'devopsteam@gmail.com', body: 'the build failed please take a look to see what happened', cc: 'teamlead@mail.com', from: '', replyTo: '', subject: 'failure', to: 'culprit@mail.com'
        }

        }

}
