language: java
jdk:
  - openjdk11
services:
  - docker
  - postgresql

before_install:
  - psql -c "create user ds_suite with encrypted password 'ds_suite_123';"
  - psql -c 'create database ds_suite;'
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull openjdk:11-jre-slim-sid
  - echo "This is a new push gjhjcheck let me see lkd to show"
script:
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install
  - ./mvnw heroku:deploy jib:build -P deploy-heroku,deploy-docker

after_success:
  - bash <(curl -s https://codecov.io/bash)
